### ISSUE TITLE
AAPT error: duplicate value

### ISSUE THREAD

**Issue by AdisAlagic** [vkay94/DoubleTapPlayerView#12]
Can't launch my app, because somehow it generates duplicate.
```
Android resource compilation failed
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:7849: AAPT: error: duplicate value for resource 'attr/show_buffering' with config ''.
    
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:7849: AAPT: error: resource previously defined here.
    
\app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml: AAPT: error: file failed to compile.
```

**Comment by vkay94** [comment]
Could you check whether cleaning the project solves the problem?
1. Build -> Clean Project
2. File -> Invalidate Caches / Restart
3. Build -> Rebuild Project

Another cause may be the different versions of ExoPlayer (version 1.0.0 of this library uses 2.11.7 and the latest is 2.12.3 which I assume you probably use) even if I don't encounter it while using 2.12.3 in the example app and 2.11.7 in the library ...

I wanted to update the dependencies anyway in the next days.

**Comment by linosistemas** [comment]
I have the same problem
