### ISSUE TITLE
how to use this in java file

### ISSUE THREAD

**Issue by Programmingtimes** [vkay94/DoubleTapPlayerView#20]
I have dev my app with java base how to implement double tab for java

**Comment by Programmingtimes** [comment]
found that asking to convert a language to another is like asking people to  rewriting entire app

**Comment by Usman-Click** [comment]
Java usage


  YouTubeOverlay youTubeOverlay = findViewById(R.id.youtube_overlay);

            youTubeOverlay.performListener(new YouTubeOverlay.PerformListener() {
                @Override
                public void onAnimationStart() {
                    // Do UI changes when circle scaling animation starts (e.g. hide controller views)
                    youTubeOverlay.setVisibility(View.VISIBLE);
                    hideSystemUI();
                }

                @Override
                public void onAnimationEnd() {
                    // Do UI changes when circle scaling animation starts (e.g. show controller views)
                    youTubeOverlay.setVisibility(View.GONE);
                }

**Comment by ThreeMinutesFix** [comment]
thankyou . do you know how to change the skip time

**Comment by Usman-Click** [comment]
@ThreeMinutesFix 
Yeah, just....

```
YouTubeOverlay youTubeOverlay = findViewById(R.id.youtube_overlay);
 youTubeOverlay.seekSeconds(10); // The Skip Time (In Seconds)
```

**Comment by ThreeMinutesFix** [comment]
thanks for your time and help
