### ISSUE TITLE
Java usage?

### ISSUE THREAD

**Issue by omkar-tenkale** [vkay94/DoubleTapPlayerView#9]
I couldn't use this library in my java project

Any help here?

**Comment by vkay94** [comment]
I built a a simple demo in Java myself a moment ago and I guess I know a possible reason.
You need to set the compile options to Java 1.8. Just add these lines to your app's `build.gradle` file inside android:
```
android {
   ...
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
```
Everything else should work fine in Java (the library is built in Kotlin, so all properties need to have the `get`-prefix in Java).
